version: "3"
services:
  qna-got:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8777:8777
    environment:
      # See rest_api/pipelines.yaml for configurations of Search & Indexing Pipeline.
      - ELASTICSEARCHDOCUMENTSTORE_PARAMS_HOST=elasticsearch
    restart: always
    depends_on:
      - elasticsearch
    # command: "/bin/bash -c 'sleep 15 && gunicorn rest_api.application:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 180'"
    # command: bash -c "sleep 1m"
  elasticsearch:
    # This will start an empty elasticsearch instance (so you have to add your documents yourself)
    # image: "elasticsearch:7.13.4"
    # If you want a demo image instead that is "ready-to-query" with some indexed Game of Thrones articles:
    image: "deepset/elasticsearch-game-of-thrones"
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
